"use client";

import * as React from "react";
import { toast } from "sonner";
import { Bell, BellOff } from "lucide-react";
import { Button } from "@/components/ui/button";

// Converts the VAPID public key (base64url, as generated by web-push) into
// the raw byte array PushManager.subscribe() actually wants — the browser
// API predates base64url being a common wire format, so this conversion is
// unavoidable boilerplate every Web Push integration needs.
function urlBase64ToUint8Array(base64String: string): Uint8Array {
  const padding = "=".repeat((4 - (base64String.length % 4)) % 4);
  const base64 = (base64String + padding).replace(/-/g, "+").replace(/_/g, "/");
  const rawData = atob(base64);
  // Uint8Array.from() (not `new Uint8Array(...)`) produces a fresh copy
  // backed by a guaranteed plain ArrayBuffer — subscribe() rejects the
  // SharedArrayBuffer-compatible generic TypeScript otherwise infers here.
  return Uint8Array.from({ length: rawData.length }, (_, i) => rawData.charCodeAt(i));
}

type Status = "checking" | "unsupported" | "denied" | "off" | "on";

export function PushNotificationsToggle() {
  const [status, setStatus] = React.useState<Status>("checking");
  const [loading, setLoading] = React.useState(false);

  React.useEffect(() => {
    async function check() {
      if (!("serviceWorker" in navigator) || !("PushManager" in window)) {
        setStatus("unsupported");
        return;
      }
      if (Notification.permission === "denied") {
        setStatus("denied");
        return;
      }
      try {
        const registration = await navigator.serviceWorker.ready;
        const existing = await registration.pushManager.getSubscription();
        setStatus(existing ? "on" : "off");
      } catch {
        setStatus("off");
      }
    }
    check();
  }, []);

  async function enable() {
    const vapidKey = process.env.NEXT_PUBLIC_VAPID_PUBLIC_KEY;
    if (!vapidKey) {
      toast.error("Push-meldingen zijn niet geconfigureerd voor deze omgeving");
      return;
    }
    setLoading(true);
    try {
      const permission = await Notification.requestPermission();
      if (permission !== "granted") {
        setStatus(permission === "denied" ? "denied" : "off");
        return;
      }
      const registration = await navigator.serviceWorker.ready;
      const subscription = await registration.pushManager.subscribe({
        userVisibleOnly: true,
        // TS's DOM lib types applicationServerKey as BufferSource backed by
        // a plain (non-shared) ArrayBuffer specifically; Uint8Array's own
        // type is generic over ArrayBufferLike (which includes
        // SharedArrayBuffer), so the browser-correct value still needs an
        // explicit cast to satisfy that narrower type.
        applicationServerKey: urlBase64ToUint8Array(vapidKey) as BufferSource,
      });
      const res = await fetch("/api/push/subscribe", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(subscription.toJSON()),
      });
      if (!res.ok) throw new Error();
      setStatus("on");
      toast.success("Push-meldingen ingeschakeld op dit apparaat");
    } catch {
      toast.error("Inschakelen mislukt");
    } finally {
      setLoading(false);
    }
  }

  async function disable() {
    setLoading(true);
    try {
      const registration = await navigator.serviceWorker.ready;
      const subscription = await registration.pushManager.getSubscription();
      if (subscription) {
        await fetch("/api/push/unsubscribe", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ endpoint: subscription.endpoint }),
        });
        await subscription.unsubscribe();
      }
      setStatus("off");
      toast.success("Push-meldingen uitgeschakeld op dit apparaat");
    } catch {
      toast.error("Uitschakelen mislukt");
    } finally {
      setLoading(false);
    }
  }

  if (status === "checking") return null;

  if (status === "unsupported") {
    return <p className="text-sm text-slate-500">Deze browser ondersteunt geen push-meldingen.</p>;
  }

  if (status === "denied") {
    return (
      <p className="text-sm text-slate-500">
        Meldingen zijn geblokkeerd voor deze site in je browserinstellingen — zet dit daar eerst
        aan om push-meldingen te ontvangen.
      </p>
    );
  }

  return (
    <div className="flex items-center gap-3">
      <p className="flex-1 text-sm text-slate-400">
        {status === "on"
          ? "Push-meldingen staan aan op dit apparaat."
          : "Ontvang een melding op dit apparaat, ook als de app niet open staat."}
      </p>
      {status === "on" ? (
        <Button size="sm" variant="outline" loading={loading} onClick={disable}>
          <BellOff className="h-4 w-4" /> Uitschakelen
        </Button>
      ) : (
        <Button size="sm" variant="secondary" loading={loading} onClick={enable}>
          <Bell className="h-4 w-4" /> Inschakelen
        </Button>
      )}
    </div>
  );
}
